let books = [
	{
		id: 10001,
		naziv: "A Game of Thrones",
		autori: ["George R. R. Martin"],
		ISBN: "978-0553103540",
		brojStranica: 694,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon"]
	},
	{
		id: 10002,
		naziv: "A Clash of Kings",
		autori: ["George R. R. Martin"],
		ISBN: "978-0553108033",
		brojStranica: 768,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10003,
		naziv: "A Storm of Swords",
		autori: ["George R. R. Martin"],
		ISBN: "978-0553106633",
		brojStranica: 992,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10004,
		naziv: "The Hedge Knight",
		autori: ["George R. R. Martin"],
		ISBN: "978-0976401100",
		brojStranica: 164,
		izdavac: "Dabel Brothers Publishing",
		zemljaPodrijetla: "United States",
		likovi: ["Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10005,
		naziv: "A Feast for Crows",
		autori: ["George R. R. Martin"],
		ISBN: "978-0553801507",
		brojStranica: 784,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10006,
		naziv: "The Sworn Sword",
		autori: ["George R. R. Martin"],
		ISBN: "978-0785126508",
		brojStranica: 152,
		izdavac: "Marvel",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy"]
	},
	{
		id: 10007,
		naziv: "The Mystery Knight",
		autori: ["George R. R. Martin"],
		ISBN: "978-0765360267",
		brojStranica: 416,
		izdavac: "Tor Fantasy",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10008,
		naziv: "A Dance with Dragons",
		autori: ["George R. R. Martin"],
		ISBN: "978-0553801477",
		brojStranica: 1040,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10009,
		naziv: "The Princess and the Queen",
		autori: ["George R. R. Martin"],
		ISBN: "978-0765332066",
		brojStranica: 784,
		izdavac: "Tor Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Daenerys Targaryen", "Jorah Mormont", "Viserys Targaryen", "Jon Snow", "Robb Stark", "Sansa Stark",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	},
	{
		id: 10010,
		naziv: "The Rogue Prince",
		autori: ["George R. R. Martin"],
		ISBN: "978-0345537263",
		brojStranica: 832,
		izdavac: "Bantam Books",
		zemljaPodrijetla: "United States",
		likovi: ["Eddard 'Ned' Stark", "Robert Baratheon", "Jaime Lannister", "Catelyn Stark", "Cersei Lannister",
		"Arya Stark", "Theon Greyjoy", "Brandon 'Bran' Stark", "Joffrey Baratheon", "Sandor Clegane", "Tyrion Lannister",
		"Petyr 'Littlefinger' Baelish", "Davos Seaworth", "Samwell Tarly", "Stannis Baratheon", "Melisandre",
		"Jeor Mormont", "Bronn", "Varys", "Shae", "Margaery Tyrell", "Tywin Lannister", "Talisa Maegyr", "Ygritte",
		"Gendry", "Tormund Giantsbane", "Brienne of Tarth", "Ramsay Bolton", "Gilly", "Daario Naharis", "Missandei",
		"Ellaria Sand", "Tommen Baratheon", "Jaqen H'ghar", "Roose Bolton", "The High Sparrow"]
	}
];

module.exports = books;